### PR TITLE
🔀 Merge Project into main

### PR DESCRIPTION
**Pull request by mgdev21**
Here are the project classes, code is commented

### CODE REVIEW

**Review by Electimore — CHANGES_REQUESTED** [review]
Code looks alright, I'd say it just needs one minor additrion: the MyDate classes and a method for getInterval to calculate it from the dates, or to estimate the end date from the interval and the startdate

Also, you could implement some kind a mechanism to automatically asign project IDs to new projects - it just feels wierd if Bob would have to just get a random number every time... (you can make it just be the index of the arrayList, or make them pseudo-random)


that's all I can think of rn

**Review by Electimore — COMMENTED** [review]
Do the other Projects know which IDs are used? By that I mean, why is the method to generate them in the Project class and not in the ProjectList. Also, they can be a bit simplified by using just the index of the project in the array - I've thought about that and I just think that it will be easier to organise later on...

Anyway, just a comment, it'd be nice if someone else said something bout that...

**Comment by mgdev21** [comment]
> Do the other Projects know which IDs are used? By that I mean, why is the method to generate them in the Project class and not in the ProjectList. Also, they can be a bit simplified by using just the index of the project in the array - I've thought about that and I just think that it will be easier to organise later on...
> 
> Anyway, just a comment, it'd be nice if someone else said something bout that...


I think it might be better to have the generation of IDs in Project, because it wont affect all the project list. When a project is created everytime it has a new ID that can not be the same. In the future we might have a problem where sometime the whole project list might get the ID. I think you get my idea.

**Comment by Electimore** [comment]
And how the projects know every other project's ID's? And nope, I don't get it why would it work like that if it were inside the projectlist... I think it would be best if we talked it through tomorrow at the meeting

**Review by Electimore — APPROVED** [review]

**Pull request merged**
